"""
Frechet differential of a nonlinear map of the plane.

The map is
    f(x, y) = (x + 0.35 sin y, y + 0.35 sin x),
with Jacobian
    df_a = [[1, 0.35 cos a_2], [0.35 cos a_1, 1]].

Left panel : the regular Cartesian grid, the base point a, two small vectors
             u, v, and the parallelogram a, a+u, a+v, a+u+v.
Right panel: the same grid transported by f, together with the true images
             f(a+u), f(a+v), f(a+u+v), and the linear parallelogram generated
             at f(a) by df_a(u) and df_a(v). Dashed segments join each linear
             approximation to the corresponding nonlinear image; their length
             is the o(||h||) remainder.

Comments and labels are in English.
"""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

OUT = Path(__file__).resolve().parent / "output"
OUT.mkdir(exist_ok=True)

AMPLITUDE = 0.35

# Base point and the two tangent vectors.
A = np.array([0.55, 0.45])
U = np.array([0.95, 0.12])
V = np.array([0.10, 0.95])

# Grid extent, sampling, and visible window (shared by the two panels).
GRID_LIM = 4.0
GRID_STEP = 0.4
N_FINE = 500
VIEW = (-0.55, 2.95)

# Palette shared with the other scripts of the paper.
GRID_SOURCE = "#9AA0A6"
GRID_IMAGE = "#4C78A8"
POINT = "#E07A35"
U_COLOR = "#C44E52"
V_COLOR = "#4C72B0"
SUM_COLOR = "#4C956C"
REMAINDER = "#6B6B6B"


def f(p):
    """f(x, y) = (x + 0.35 sin y, y + 0.35 sin x)."""
    p = np.asarray(p, dtype=float)
    x, y = p[..., 0], p[..., 1]
    return np.stack([x + AMPLITUDE * np.sin(y), y + AMPLITUDE * np.sin(x)], axis=-1)


def df(a, h):
    """Differential of f at a, applied to h."""
    a = np.asarray(a, dtype=float)
    jacobian = np.array(
        [
            [1.0, AMPLITUDE * np.cos(a[1])],
            [AMPLITUDE * np.cos(a[0]), 1.0],
        ]
    )
    return jacobian @ np.asarray(h, dtype=float)


def grid_lines():
    """Coordinate lines of the Cartesian grid, finely sampled."""
    fine = np.linspace(-GRID_LIM, GRID_LIM, N_FINE)
    n_nodes = int(round(2.0 * GRID_LIM / GRID_STEP)) + 1
    nodes = np.linspace(-GRID_LIM, GRID_LIM, n_nodes)
    lines = []
    for value in nodes:
        lines.append(np.column_stack([fine, np.full_like(fine, value)]))
        lines.append(np.column_stack([np.full_like(fine, value), fine]))
    return lines


def draw_arrow(ax, origin, vector, color, label, offset, anchor=0.55):
    """Arrow from `origin`, labelled at `anchor` along it plus `offset`."""
    ax.annotate(
        "",
        xy=origin + vector,
        xytext=origin,
        arrowprops=dict(arrowstyle="-|>", color=color, lw=2.0, mutation_scale=11),
        zorder=10,
    )
    position = origin + anchor * vector + offset
    ax.text(position[0], position[1], label, color=color, fontsize=10, zorder=11)


def draw_parallelogram(ax, origin, first, second, color, ls, alpha):
    corners = np.array(
        [origin, origin + first, origin + first + second, origin + second, origin]
    )
    ax.fill(corners[:, 0], corners[:, 1], color=color, alpha=alpha, zorder=2)
    ax.plot(corners[:, 0], corners[:, 1], color=color, lw=1.1, ls=ls, zorder=3)


LINES = grid_lines()

fig, (ax_source, ax_image) = plt.subplots(1, 2, figsize=(11.4, 5.6))

# ---------------------------------------------------------------------------
# Left: the source plane
# ---------------------------------------------------------------------------
for line in LINES:
    ax_source.plot(line[:, 0], line[:, 1], color=GRID_SOURCE, lw=0.6, alpha=0.85)

draw_parallelogram(ax_source, A, U, V, POINT, "-", 0.16)
draw_arrow(ax_source, A, U, U_COLOR, r"$u$", np.array([0.0, -0.22]))
draw_arrow(ax_source, A, V, V_COLOR, r"$v$", np.array([-0.22, 0.0]))
ax_source.plot(*A, "o", color=POINT, mec="white", mew=1.2, ms=9, zorder=12)
ax_source.text(A[0] - 0.26, A[1] - 0.22, r"$a$", color=POINT, fontsize=11, zorder=12)
ax_source.text(
    *(A + U + np.array([0.05, 0.06])), r"$a+u$", color=POINT, fontsize=9, zorder=12
)
ax_source.text(
    *(A + V + np.array([-0.62, 0.06])), r"$a+v$", color=POINT, fontsize=9, zorder=12
)
ax_source.text(
    *(A + U + V + np.array([0.06, 0.08])),
    r"$a+u+v$",
    color=POINT,
    fontsize=9,
    zorder=12,
)
ax_source.set_title(r"Source plane: $a$, $u$, $v$", fontsize=11)

# ---------------------------------------------------------------------------
# Right: the image plane, nonlinear images against the linear model
# ---------------------------------------------------------------------------
for line in LINES:
    image = f(line)
    ax_image.plot(image[:, 0], image[:, 1], color=GRID_IMAGE, lw=0.6, alpha=0.85)

f_a = f(A)
du, dv = df(A, U), df(A, V)

# Exact linear parallelogram generated by df_a(u) and df_a(v).
draw_parallelogram(ax_image, f_a, du, dv, POINT, "-", 0.16)

# True nonlinear images and the remainder segments.
targets = [
    (f(A + U), f_a + du, r"$f(a+u)$", np.array([0.09, -0.16])),
    (f(A + V), f_a + dv, r"$f(a+v)$", np.array([-0.72, 0.06])),
    (f(A + U + V), f_a + du + dv, r"$f(a+u+v)$", np.array([0.10, -0.05])),
]
for true_point, linear_point, label, offset in targets:
    ax_image.plot(
        [linear_point[0], true_point[0]],
        [linear_point[1], true_point[1]],
        ls="--",
        color=REMAINDER,
        lw=1.1,
        zorder=8,
    )
    ax_image.plot(
        *true_point, "o", color=GRID_IMAGE, mec="white", mew=1.1, ms=7, zorder=11
    )
    ax_image.text(
        *(true_point + offset), label, color=GRID_IMAGE, fontsize=9, zorder=12
    )

draw_arrow(ax_image, f_a, du, U_COLOR, r"$df_{a}(u)$", np.array([-0.10, -0.28]))
draw_arrow(ax_image, f_a, dv, V_COLOR, r"$df_{a}(v)$", np.array([-0.62, -0.02]))
ax_image.annotate(
    "",
    xy=f_a + du + dv,
    xytext=f_a,
    arrowprops=dict(arrowstyle="-|>", color=SUM_COLOR, lw=1.8, mutation_scale=11),
    zorder=9,
)
ax_image.text(
    0.03,
    0.05,
    r"$df_{a}(u+v)=df_{a}(u)+df_{a}(v)$",
    transform=ax_image.transAxes,
    color=SUM_COLOR,
    fontsize=10,
    zorder=12,
)
ax_image.plot(*f_a, "o", color=POINT, mec="white", mew=1.2, ms=9, zorder=12)
ax_image.text(
    f_a[0] - 0.34, f_a[1] - 0.24, r"$f(a)$", color=POINT, fontsize=11, zorder=12
)
ax_image.set_title(
    r"Image plane: $f$ against the linear map $df_{a}$", fontsize=11
)

for ax in (ax_source, ax_image):
    ax.set_aspect("equal")
    ax.set_xlim(*VIEW)
    ax.set_ylim(*VIEW)
    ax.set_xticks([])
    ax.set_yticks([])
    for side in ("top", "right", "bottom", "left"):
        ax.spines[side].set_visible(False)

fig.suptitle(
    r"$f(a+h)=f(a)+df_{a}(h)+o(\|h\|)$: "
    r"dashed segments are the remainder",
    y=0.97,
    fontsize=12,
)
fig.subplots_adjust(left=0.02, right=0.98, top=0.88, bottom=0.03, wspace=0.06)

path = OUT / "36_frechet_differential.png"
fig.savefig(path, dpi=200, bbox_inches="tight", facecolor="white")
print(f"Wrote {path}")
for true_point, linear_point, label, _ in targets:
    print(f"{label}: remainder = {np.linalg.norm(true_point - linear_point):.4f}")
# plt.show()  # uncomment for interactive display
